export const nightlyWolfSoftTheme = {
  name: "Nightly Wolf Soft",
  displayName: "Nightly Wolf Soft",
  editorBackground: "#141d2b",
  editorForeground: "#F8F8F2",
  activityBarBackground: "#141d2b",
  activityBarForeground: "#a4b1cd",
  activityBarInActiveForeground: "#313f55",
  activityBarBorder: "#141d2b",
  activityBarActiveBorder: "#ff3e3e",
  activityBarActiveBackground: "#141d2b",
  activityBarBadgeBackground: "#a12020",
  activityBarBadgeForeground: "#ffffff",
  tabsContainerBackground: "#111927",
  tabsContainerBorder: "#141d2b",
  statusBarBackground: "#1a2332",
  statusBarForeground: "#a4b1cd",
  statusBarBorder: "#1a2332",
  tabActiveBackground: "#1a2332",
  tabInactiveBackground: "#141d2b",
  tabActiveForeground: "#ffffff",
  tabBorder: "#141d2b",
  tabActiveBorder: "#1a2332",
  tabActiveBorderTop: "#ff3e3e",
  titleBarActiveBackground: "#141d2b",
  titleBarActiveForeground: "#a4b1cd",
  titleBarBorder: "#141d2b",
} as const;
