export const nightlyWolfWhiteTheme = {
  name: "Nightly Wolf White",
  displayName: "Nightly Wolf Light",
  editorBackground: "#ffffff",
  editorForeground: "#2d3748",
  activityBarBackground: "#f7fafc",
  activityBarForeground: "#2d3748",
  activityBarInActiveForeground: "#a0aec0",
  activityBarBorder: "#edf2f7",
  activityBarActiveBorder: "#ff3e3e",
  activityBarActiveBackground: null,
  activityBarBadgeBackground: "#ff3e3e",
  activityBarBadgeForeground: "#ffffff",
  tabsContainerBackground: "#f7fafc",
  tabsContainerBorder: "#edf2f7",
  statusBarBackground: "#f7fafc",
  statusBarForeground: "#2d3748",
  statusBarBorder: "#edf2f7",
  tabActiveBackground: "#ffffff",
  tabInactiveBackground: "#f7fafc",
  tabActiveForeground: "#2d3748",
  tabBorder: "#edf2f7",
  tabActiveBorder: "#ffffff",
  tabActiveBorderTop: "#ff3e3e",
  titleBarActiveBackground: "#f7fafc",
  titleBarActiveForeground: "#718096",
  titleBarBorder: "#edf2f7",
} as const;
