export const nightlyWolfTheme = {
  name: "Nightly Wolf",
  displayName: "Nightly Wolf Dark",
  editorBackground: "#181421",
  editorForeground: "#a4b1cd",
  activityBarBackground: "#110F18",
  activityBarForeground: "#a4b1cd",
  activityBarInActiveForeground: "#313f55",
  activityBarBorder: "#0a080e",
  activityBarActiveBorder: "#ff3e3e",
  activityBarActiveBackground: null,
  activityBarBadgeBackground: "#a12020",
  activityBarBadgeForeground: "#ffffff",
  tabsContainerBackground: "#13101a",
  tabsContainerBorder: "#0a080e",
  statusBarBackground: "#181421",
  statusBarForeground: "#a4b1cd",
  statusBarBorder: null,
  tabActiveBackground: "#181421",
  tabInactiveBackground: "#13101a",
  tabActiveForeground: "#9698d8",
  tabBorder: "#0a080e",
  tabActiveBorder: "#181421",
  tabActiveBorderTop: "#d5d5e4",
  titleBarActiveBackground: "#13101a",
  titleBarActiveForeground: "#52456f",
  titleBarBorder: "#0a080e",
} as const;
