export type Theme = {
  name: string;
  displayName: string;
  editorBackground: string;
  editorForeground: string;
  activityBarBackground: string;
  activityBarForeground: string;
  activityBarInActiveForeground: string;
  activityBarBorder: string | null;
  activityBarActiveBorder: string;
  activityBarActiveBackground: string | null;
  activityBarBadgeBackground: string;
  activityBarBadgeForeground: string;
  tabsContainerBackground: string;
  tabsContainerBorder: string | null;
  statusBarBackground: string;
  statusBarForeground: string;
  statusBarBorder: string | null;
  tabActiveBackground: string;
  tabInactiveBackground: string;
  tabActiveForeground: string;
  tabBorder: string;
  tabActiveBorder: string;
  tabActiveBorderTop: string;
  titleBarActiveBackground: string;
  titleBarActiveForeground: string;
  titleBarBorder: string;
};
